/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_bupt_sensordriver_sensor */

#ifndef _Included_com_bupt_sensordriver_sensor
#define _Included_com_bupt_sensordriver_sensor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_bupt_sensordriver_sensor
 * Method:    Open
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_bupt_sensordriver_sensor_Open
  (JNIEnv *, jobject);

/*
 * Class:     com_bupt_sensordriver_sensor
 * Method:    Close
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_bupt_sensordriver_sensor_Close
  (JNIEnv *, jobject);

/*
 * Class:     com_bupt_sensordriver_sensor
 * Method:    Ioctl
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_bupt_sensordriver_sensor_Ioctl
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_bupt_sensordriver_sensor
 * Method:    Read
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_com_bupt_sensordriver_sensor_Read
//JNIEXPORT jcharArray JNICALL Java_com_bupt_sensordriver_sensor_Read
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
