/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_bupt_sensordriver_rfid */

#ifndef _Included_com_bupt_sensordriver_rfid
#define _Included_com_bupt_sensordriver_rfid
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_bupt_sensordriver_rfid
 * Method:    Open
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_bupt_sensordriver_rfid_Open
  (JNIEnv *, jobject);

/*
 * Class:     com_bupt_sensordriver_rfid
 * Method:    Close
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_bupt_sensordriver_rfid_Close
  (JNIEnv *, jobject);

/*
 * Class:     com_bupt_sensordriver_rfid
 * Method:    Ioctl
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_bupt_sensordriver_rfid_Ioctl
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_bupt_sensordriver_rfid
 * Method:    Read
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_com_bupt_sensordriver_rfid_Read
  (JNIEnv *, jobject);

/*
 * Class:     com_bupt_sensordriver_rfid
 * Method:    ReadCardNum
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_bupt_sensordriver_rfid_ReadCardNum
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
